invoice/urls.py
from django.urls import path
from . import views

urlpatterns = [
path('login',views.login, name='login'),
path('logout',views.logout, name='logout'),
path('',views.dashboard, name='dashboard'),
path('invoices',views.invoices, name='invoices'),
path('products',views.products, name='products'),
path('clients',views.clients, name='clients'),

#Create URL Paths
path('invoices/create',views.createInvoice, name='create-invoice'),
path('invoices/create-build/<slug:slug>',views.createBuildInvoice, name='create-build-invoice'),

#Delete an invoice
path('invoices/delete/<slug:slug>',views.deleteInvoice, name='delete-invoice'),

#PDF and EMAIL Paths
path('invoices/view-pdf/<slug:slug>',views.viewPDFInvoice, name='view-pdf-invoice'),
]

invoicing/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf import settings
from django.conf.urls.static import static

from invoice import views as invoice_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('invoice.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

invoice/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.utils import timezone
from uuid import uuid4
from django.contrib.auth.models import User



class Client(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    clientName = models.CharField(null=True, blank=True, max_length=200)
    addressLine1 = models.CharField(null=True, blank=True, max_length=200)
    province = models.CharField(null=True, blank=True, max_length=100)
    phoneNumber = models.CharField(null=True, blank=True, max_length=100)
    taxNumber = models.CharField(null=True, blank=True, max_length=100)
    houseNumber = models.CharField(null=True, blank=True, max_length=100)
    meterNumber = models.CharField(null=True, blank=True, max_length=100)


    #Utility fields
    uniqueId = models.CharField(null=True, blank=True, max_length=100)
    slug = models.SlugField(max_length=500, unique=True, blank=True, null=True)
    date_created = models.DateTimeField(blank=True, null=True)
    last_updated = models.DateTimeField(blank=True, null=True)


    def __str__(self):
        return '{} {} '.format(self.clientName, self.province)


    def get_absolute_url(self):
        return reverse('client-detail', kwargs={'slug': self.slug})


    def save(self, *args, **kwargs):
        if self.date_created is None:
            self.date_created = timezone.localtime(timezone.now())
        if self.uniqueId is None:
            self.uniqueId = str(uuid4()).split('-')[4]
            self.slug = slugify('{} {} {}'.format(self.clientName, self.province, self.uniqueId))

        self.slug = slugify('{} {} {}'.format(self.clientName, self.province, self.uniqueId))
        self.last_updated = timezone.localtime(timezone.now())

        super(Client, self).save(*args, **kwargs)



class Invoice(models.Model):
    TERMS = [
    ('30 days', '30 days'),
    ('60 days', '60 days'),
    ]

    STATUS = [
    ('CURRENT', 'CURRENT'),
    ('EMAIL_SENT', 'EMAIL_SENT'),
    ('OVERDUE', 'OVERDUE'),
    ('PAID', 'PAID'),
    ]

    title = models.CharField(null=True, blank=True, max_length=100)
    number = models.CharField(null=True, blank=True, max_length=100)
    dueDate = models.DateField(null=True, blank=True)
    paymentTerms = models.CharField(choices=TERMS, default='30 days', max_length=100)
    status = models.CharField(choices=STATUS, default='CURRENT', max_length=100)
    notes = models.TextField(null=True, blank=True)

    #RELATED fields
    client = models.ForeignKey(Client, blank=True, null=True, on_delete=models.SET_NULL)

    #Utility fields
    uniqueId = models.CharField(null=True, blank=True, max_length=100)
    slug = models.SlugField(max_length=500, unique=True, blank=True, null=True)
    date_created = models.DateTimeField(blank=True, null=True)
    last_updated = models.DateTimeField(blank=True, null=True)


    def __str__(self):
        return '{} {}'.format(self.number, self.status)


    def get_absolute_url(self):
        return reverse('invoice-detail', kwargs={'slug': self.slug})


    def save(self, *args, **kwargs):
        if self.date_created is None:
            self.date_created = timezone.localtime(timezone.now())
        if self.uniqueId is None:
            self.uniqueId = str(uuid4()).split('-')[4]
            self.slug = slugify('{} {}'.format(self.number, self.uniqueId))

        self.slug = slugify('{} {}'.format(self.number, self.uniqueId))
        self.last_updated = timezone.localtime(timezone.now())

        super(Invoice, self).save(*args, **kwargs)



class Product(models.Model):
    CURRENCY = [
    ('Ksh', 'KES'),
    ('$', 'USD'),
    ]

    title = models.DateField()
    quantity = models.FloatField(null=True, blank=True)
    price = models.FloatField(null=True, blank=True)
    total = models.FloatField(null=True, blank=True)
    currency = models.CharField(choices=CURRENCY, default='R', max_length=100)

    #Related Fields
    invoice = models.ForeignKey(Invoice, blank=True, null=True, on_delete=models.CASCADE)

    #Utility fields
    uniqueId = models.CharField(null=True, blank=True, max_length=100)
    slug = models.SlugField(max_length=500, unique=True, blank=True, null=True)
    date_created = models.DateTimeField(blank=True, null=True)
    last_updated = models.DateTimeField(blank=True, null=True)


    def __str__(self):
        return '{}'.format(self.title)


    def get_absolute_url(self):
        return reverse('product-detail', kwargs={'slug': self.slug})


    def save(self, *args, **kwargs):
        if self.date_created is None:
            self.date_created = timezone.localtime(timezone.now())
        if self.uniqueId is None:
            self.uniqueId = str(uuid4()).split('-')[4]
            self.slug = slugify('{} {}'.format(self.title, self.uniqueId))

        if self.quantity is not None and self.price is not None:
            self.total = self.quantity * self.price
        super().save(*args, **kwargs)

        self.slug = slugify('{} {}'.format(self.title, self.uniqueId))
        self.last_updated = timezone.localtime(timezone.now())

        super(Product, self).save(*args, **kwargs)

invoice/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.decorators import user_passes_test
from django.shortcuts import render, redirect
from django.contrib import messages
from django.conf import settings
from .forms import *
from .models import *
from .functions import *

from django.contrib.auth.models import User, auth
from random import randint
from uuid import uuid4

from django.http import HttpResponse

import pdfkit
from django.template.loader import get_template
import os


#Anonymous required
def anonymous_required(function=None, redirect_url=None):

   if not redirect_url:
       redirect_url = 'dashboard'

   actual_decorator = user_passes_test(
       lambda u: u.is_anonymous,
       login_url=redirect_url
   )

   if function:
       return actual_decorator(function)
   return actual_decorator


def index(request):
    context = {}
    return render(request, 'invoice/index.html', context)


@anonymous_required
def login(request):
    context = {}
    if request.method == 'GET':
        form = UserLoginForm()
        context['form'] = form
        return render(request, 'invoice/login.html', context)

    if request.method == 'POST':
        form = UserLoginForm(request.POST)

        username = request.POST['username']
        password = request.POST['password']

        user = auth.authenticate(username=username, password=password)
        if user is not None:
            auth.login(request, user)

            return redirect('dashboard')
        else:
            context['form'] = form
            messages.error(request, 'Invalid Credentials')
            return redirect('login')


    return render(request, 'invoice/login.html', context)


@login_required
def dashboard(request):
    clients = Client.objects.all().count()
    invoices = Invoice.objects.all().count()
    paidInvoices = Invoice.objects.filter(status='PAID').count()
    labels = []
    data = []

    if request.user.is_staff:
        stockqueryset = Product.objects.all()
        for item in stockqueryset:
            labels.append(item.quantity)
            data.append(item.total)
           
    else:
        stockqueryset = Invoice.objects.filter(client=request.user.client)
        bills = Invoice.objects.filter(client=request.user.client).count()
        for item in stockqueryset:
            labels.append(item.status)
            data.append(bills)


    context = {
        'labels': labels,
        'data': data,
        'clients': clients,
        'invoices': invoices
     }
    
    return render(request, 'invoice/dashboard.html', context)




@login_required
def invoices(request):
    if request.user.is_staff:
        # Admin can see all invoices
        invoices = Invoice.objects.all()
    else:
        # Non-admin user (client) can only see their related invoices
        invoices = Invoice.objects.filter(client=request.user.client)
        
    return render(request, 'invoice/invoices.html', {'invoices': invoices})


@login_required
def products(request):
    products = Product.objects.all()

    return render(request, 'invoice/products.html', {'products': products})



@login_required
def clients(request):
    clients = Client.objects.all()

    if request.method == 'GET':
        form = ClientForm()
        user_form = UserForm()
        return render(request, 'invoice/clients.html', {'clients': clients,'form':form, 'user_form': user_form})

    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        form = ClientForm(request.POST, request.FILES)

        

        if user_form.is_valid() and form.is_valid():
            user = user_form.save()
            user.save()

            profile = form.save(commit=False)
            profile.user = user
            profile.save()

            messages.success(request, 'New Client Added')
            return redirect('clients')
        else:
            messages.error(request, 'Problem processing your request')
            return redirect('clients')
    else:
        user_form = UserForm()
        form = ClientForm()


    return render(request, 'invoice/clients.html', {'clients': clients,
                             'user_form':user_form,
                             'form':form})



@login_required
def logout(request):
    auth.logout(request)
    return redirect('login')


###--------------------------- Create Invoice Views Start here --------------------------------------------- ###

@login_required
def createInvoice(request):
    #create a blank invoice ....
    number = 'INV-'+str(uuid4()).split('-')[1]
    newInvoice = Invoice.objects.create(number=number)
    newInvoice.save()

    inv = Invoice.objects.get(number=number)
    return redirect('create-build-invoice', slug=inv.slug)




def createBuildInvoice(request, slug):
    #fetch that invoice
    try:
        invoice = Invoice.objects.get(slug=slug)
        pass
    except:
        messages.error(request, 'Something went wrong')
        return redirect('invoices')

    #fetch all the products - related to this invoice
    products = Product.objects.filter(invoice=invoice)


    context = {}
    context['invoice'] = invoice
    context['products'] = products

    if request.method == 'GET':
        prod_form  = ProductForm()
        inv_form = InvoiceForm(instance=invoice)
        client_form = ClientSelectForm(initial_client=invoice.client)
        context['prod_form'] = prod_form
        context['inv_form'] = inv_form
        context['client_form'] = client_form
        return render(request, 'invoice/create-invoice.html', context)

    if request.method == 'POST':
        prod_form  = ProductForm(request.POST)
        inv_form = InvoiceForm(request.POST, instance=invoice)
        client_form = ClientSelectForm(request.POST, initial_client=invoice.client, instance=invoice)

        if prod_form.is_valid():
            obj = prod_form.save(commit=False)
            obj.invoice = invoice
            obj.save()

            messages.success(request, "Invoice product added succesfully")
            return redirect('create-build-invoice', slug=slug)
        elif inv_form.is_valid and 'paymentTerms' in request.POST:
            inv_form.save()

            messages.success(request, "Invoice updated succesfully")
            return redirect('create-build-invoice', slug=slug)
        elif client_form.is_valid() and 'client' in request.POST:

            client_form.save()
            messages.success(request, "Client added to invoice succesfully")
            return redirect('create-build-invoice', slug=slug)
        else:
            context['prod_form'] = prod_form
            context['inv_form'] = inv_form
            context['client_form'] = client_form
            messages.error(request,"Problem processing your request")
            return render(request, 'invoice/create-invoice.html', context)


    return render(request, 'invoice/create-invoice.html', context)




def viewPDFInvoice(request, slug):
    #fetch that invoice
    try:
        invoice = Invoice.objects.get(slug=slug)
        pass
    except:
        messages.error(request, 'Something went wrong')
        return redirect('invoices')

    #fetch all the products - related to this invoice
    products = Product.objects.filter(invoice=invoice)


    #Calculate the Invoice Total
    invoiceCurrency = ''
    invoiceTotal = 0.0
    if len(products) > 0:
        for x in products:
            y = float(x.quantity) * float(x.price)
            invoiceTotal += y
            invoiceCurrency = x.currency

    return render(request, 'invoice/water-bill.html', {'invoice':invoice,'products': products,'invoiceTotal':"{:.2f}".format(invoiceTotal), 'invoiceCurrency': invoiceCurrency })



def deleteInvoice(request, slug):
    try:
        Invoice.objects.get(slug=slug).delete()
    except:
        messages.error(request, 'Something went wrong')
        return redirect('invoices')

    return redirect('invoices')































###
##
#

templates/invoice/clients.html
{% extends 'partials/base.html' %}
{% load static %}
{% load crispy_forms_tags %}


{% block css %}
<link href="{% static 'assets/css/bootstrap.min.css' %}" rel="stylesheet">
{% endblock %}




{% block main %}

  <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
    <h1 class="h2">Clients</h1>
    {% if request.user.is_superuser %}
    <div class="btn-toolbar mb-2 mb-md-0">
      <div class="btn-group me-2">
        <button href="#addClientModal" type="button" class="btn btn-primary" data-bs-toggle="modal">Add New Client</button>
      </div>
    </div>
    {% endif %}
  </div>

  <!-- <canvas class="my-4 w-100" id="myChart" width="900" height="380"></canvas> -->

  {% if clients|length > 0 %}
  <div class="table-responsive">
    <table class="table table-striped table-sm">
      <thead>
        <tr>
          <th scope="col">Client Name</th>
          <th scope="col">House Number</th>
          <th scope="col">Phone Number</th>
          <th scope="col">Meter Number</th>
          <th scope="col">Province</th>
        </tr>
      </thead>
      <tbody>

        {% for client in clients %}
      <tr>
        <td>{{client.clientName}}</td>
        <td>{{client.houseNumber}}</td>
        <td>{{client.phoneNumber}}</td>
        <td>{{client.meterNumber}}</td>
        <td>{{client.province}}</td>
      </tr>
        {% endfor %}

      </tbody>
    </table>
  </div>
  {% else %}
  <div class="row">
    <div class="col-lg-2">

    </div>
    <div class="col-lg-8">
      <h3>Add First Client</h3>
      <!-- <img class=img-fluid  src="{% static 'assets/img/empty.svg' %}" > -->
    </div>
    <div class="col-lg-3">

    </div>
  </div>
  {% endif %}



<!-- MODALS MODALS -->
  <!-- Modals Start Here -->
  <div class="modal modal-sheet py-5" tabindex="-1" id="addClientModal">
  <div class="modal-dialog">
    <div class="modal-content rounded-6 shadow">

      <form class="" action="#" method="post" enctype="multipart/form-data">
        {% csrf_token %}


      <div class="modal-header border-bottom-0">
        <h5 class="modal-title">Add new client</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>

      <div class="modal-body py-0">
        
        
        {{form|crispy}}
        <p><strong> --------- User Account  ---------</strong></p>
        {{ user_form|crispy }}

      </div>
      <div class="modal-footer flex-column border-top-0">
        <button type="submit" class="btn btn-lg btn-primary w-100 mx-0 mb-2">Save changes</button>
      </div>

      </form>
    </div>
  </div>
</div>


{% endblock %}

templates/invoice/create-invoice.html
{% extends 'partials/base.html' %}
{% load static %}
{% load crispy_forms_tags %}


{% block css %}
<link href="{% static 'assets/css/bootstrap.min.css' %}" rel="stylesheet">
{% endblock %}




{% block main %}



  <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
    
    {% if request.user.is_superuser %}
    <h1 class="h2">Create a Water Bill </h1>
    {% else  %}
    <h1 class="h2">Water Bills </h1>
    {% endif %}
    <div class="btn-toolbar mb-2 mb-md-0">
      <div class="btn-group me-2">
        <a href="{% url 'invoices' %}"><button type="button" class="btn btn-primary">Go Back</button></a>
      </div>
    </div>
  </div>



    <div class="container-fluid">
    <div class="card">
      <div class="card-header">
        Water Bill Generator
      </div>

      <div class="card-body">

        <div class="row">
          <div class="col-lg-12">
            {% if request.user.is_superuser %}
            <h5 class="card-title">To Add Todays Meter Reading select a client First
              <button href="#addProductModal" id="id_client" type="button" class="btn btn-outline-success" onclick="return validateClientSelection();" data-bs-toggle="modal"> Add Meter Reading </button>
            </h5>
            {% endif %}
            {% if products|length > 0 %}
            <div class="table-responsive">
              <table class="table table-striped table-sm">
                <thead>
                  <tr>

                    <th>Date</th>
                    <th>Quantity(Liters)</th>
                    <th>Price(Per Litre)</th>
                    <th>Total</th>

                  </tr>
                </thead>
                <tbody>

                  {% for product in products %}
                <tr>
                  <td>{{product.title}}</td>
                  <td>{{product.quantity}}</td>
                  <td>{{product.currency}} {{product.price}}</td>
                  <td>{{product.currency}} {{product.total}}</td>
                </tr>
                  {% endfor %}

                </tbody>
              </table>
            </div>
            {% endif %}
          </div>
        </div>

        <br>


        <div class="row">
          <div class="col-lg-6">

            <form class="" action="#" method="post">

              {% csrf_token %}
              {{ form|crispy }}

            </form>

          </div>
          
          <div class="col-lg-6">
            {% if request.user.is_superuser %}
            <h5 class="card-title"> Select Client to Add </h5>
            <br>
            <h5 class="card-title"> Current Client: <span class="badge bg-success"> {{invoice.client.clientName}}</span> </h5>
            <br>

            <div class="mb-5">
              <form class="" action="#" method="post">
                {% csrf_token %}
                {{client_form|crispy}}

                <button type="submit" class="btn btn-primary">ADD CLIENT</button>
              </form>
            </div>
            {% endif %}
            <div class="row">
              <div class="col-lg-4">
                <a href="{% url 'view-pdf-invoice' invoice.slug %}"><button class="btn btn-info text-white"> VIEW CLIENT INVOICE </button></a>
              </div>
            </div>


          </div>
        </div>




      </div>
    </div>
  </div>





  <!-- MODALS MODALS -->
    <!-- Modals Start Here -->
    <div class="modal modal-sheet py-5" tabindex="-1" id="addProductModal">
    <div class="modal-dialog">
      <div class="modal-content rounded-6 shadow">

        <form class="" action="#"  method="post" enctype="multipart/form-data">
          {% csrf_token %}


        <div class="modal-header border-bottom-0">
          <h5 class="modal-title">Add Meter Reading</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>

        <div class="modal-body py-0">

          {{ prod_form|crispy }}
          {{ form.media }}

        </div>
        <div class="modal-footer flex-column border-top-0">
          <button type="submit" class="btn btn-lg btn-primary w-100 mx-0 mb-2">Save changes</button>
        </div>

        </form>
      </div>
    </div>
  </div>
  <script>

    function validateClientSelection() {
      document.addEventListener("DOMContentLoaded", function () {
        var currentClient = "{{invoice.client.clientName}}";
        if (!currentClient) {
          alert("Please select a client first.");
        }
      });
    }
  </script>

{% endblock %}

templates/invoice/dashboard.html
{% extends 'partials/base.html' %}

{% load static %}
{% load crispy_forms_tags %}


{% block main %}


  <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
    <h1 class="h2">Dashboard</h1>
    <div class="btn-toolbar mb-2 mb-md-0">
      <div class="btn-group me-2">

      </div>
    </div>
  </div>


  <div class="container">
    {% if request.user.is_superuser %}
            <h1> Earnings  (Litres: Ksh)</h1>
    {% else  %}
             <!-- <h1> Spending  (Litres: Ksh)</h1> -->
    {% endif %}
    <br>

    <div id="container" style="position: relative; height:45vh; border: 1.2mm ridge #4e6570; border-radius: 30px;" class="align-middle table-bordered">
        <canvas id="bar-graph"></canvas>
    </div>

    <br>

    <!-- Loading Chart JS -->

    <div class="row">
      <div class="col-lg-6">
        <div class="row">
          <div class="col-lg-12">

            <div class="card mb-3">
                <h5 class="card-header">Invoices</h5>
                <div class="card-body">
                  <h5 class="card-title m-2">Total Number of  Water Bills: {{invoices}}</h5>
                  <!-- <h5 class="card-title m-2">Paid  Water Bill: {{paidInvoices}}</h5> -->
                  <a href="{% url 'invoices' %}" class="btn btn-primary btn-lg m-2">View  Water Bills</a>
                </div>
              </div>
              {% if request.user.is_superuser %}
              <div class="card mb-3">
                  <h5 class="card-header">Clients</h5>
                  <div class="card-body">
                    <h5 class="card-title m-2">Total Number of Clients: {{clients}}</h5>
                    <a href="{% url 'clients' %}" class="btn btn-primary btn-lg m-2">View Clients</a>
                  </div>
                </div>
              {% endif %}
          </div>
        </div>
      </div>
    </div>
  </div>


  <script src="{% static 'assets/js/Chart.min.js' %}"></script>
  <script>
      Chart.defaults.global.defaultFontColor = '#3c3c3c';

      //configuration for the bar graph
      var barConfig = {
          type: 'polarArea',
          data: {
              datasets: [{
                  backgroundColor:[ '#1a79a5','rgb(255, 99, 132)','rgb(54, 162, 235)','rgb(255, 205, 86)'],
                  label: 'Stock in Inventory',
                  data: {{ data|safe }},
              }],
              labels: {{ labels|safe }}
          },
          options: {
              responsive: true,
              maintainAspectRatio: false,
          },
      };


      //runs all charts on loading the webpage
      window.onload = function() {
          var ctx = document.getElementById('bar-graph').getContext('2d');
          window.BarStock = new Chart(ctx, barConfig);
      };

  </script>

{% endblock %}

templates/invoice/invoice-template.html
<!DOCTYPE html>
<html>
	{% load static %}
	<head>
		<meta charset="utf-8" />
		<title>Invoice</title>
		<link href="{% static 'assets/css/bootstrap.min.css' %}" rel="stylesheet">
		<style>
			.invoice-box {
				max-width: 800px;
				margin: auto;
				padding: 30px;
				border: 1px solid #eee;
				box-shadow: 0 0 10px rgba(0, 0, 0, 0.15);
				font-size: 16px;
				line-height: 24px;
				font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif;
				color: #555;
			}

			.invoice-box table {
				width: 100%;
				line-height: inherit;
				text-align: left;
			}

			.invoice-box table td {
				padding: 5px;
				vertical-align: top;
			}

			.invoice-box table tr td:nth-child(2) {
				text-align: right;
			}

			.invoice-box table tr.top table td {
				padding-bottom: 20px;
			}

			.invoice-box table tr.top table td.title {
				font-size: 45px;
				line-height: 45px;
				color: #333;
			}

			.invoice-box table tr.information table td {
				padding-bottom: 40px;
			}

			.invoice-box table tr.heading td {
				background: #eee;
				border-bottom: 1px solid #ddd;
				font-weight: bold;
			}

			.invoice-box table tr.details td {
				padding-bottom: 20px;
			}

			.invoice-box table tr.item td {
				border-bottom: 1px solid #eee;
			}

			.invoice-box table tr.item.last td {
				border-bottom: none;
			}

			.invoice-box table tr.total td:nth-child(2) {
				border-top: 2px solid #eee;
				font-weight: bold;
			}

			@media only screen and (max-width: 600px) {
				.invoice-box table tr.top table td {
					width: 100%;
					display: block;
					text-align: center;
				}

				.invoice-box table tr.information table td {
					width: 100%;
					display: block;
					text-align: center;
				}
			}

			/** RTL **/
			.invoice-box.rtl {
				direction: rtl;
				font-family: Tahoma, 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif;
			}

			.invoice-box.rtl table {
				text-align: right;
			}

			.invoice-box.rtl table tr td:nth-child(2) {
				text-align: left;
			}
		</style>
	</head>


	<body id="printArea">
		<div class="wrapper m-4">
			<button class="center btn btn-outline-primary" onclick="printpage('printArea')">Print</button>
		</div>
		<div  class="invoice-box">



			<table cellpadding="0" cellspacing="0">
				<tr class="top">
					<td colspan="2">
						<table>

              <tr >
      					<td><h1>Water Bill : {{p_settings.clientName}}</h1></td>
      				</tr>

							<tr>
								<td class="title">
									<img src="{% static 'assets/img/logo.jpeg' %}" style="width: 100%; max-width: 100px" />
								</td>

								<td>
									Invoice #: {{invoice.number}}<br />
									Created: {{invoice.date_created|date}}<br />
									Due: {{invoice.dueDate}}
								</td>
							</tr>
						</table>
					</td>
				</tr>

				<tr class="information">
					<td colspan="2">
						<table>
							<tr>
		

								<td>
                  {{invoice.client.clientName}}<br />
									{{invoice.client.addressLine1}}<br />
									{{invoice.client.province}}, {{invoice.client.postalCode}}<br />
									{{invoice.client.emailAddress}} <br/ >
                  {{invoice.client.phoneNumber}}
								</td>
							</tr>
						</table>
					</td>
				</tr>


				<tr class="heading">
					<td>Date</td>
          <td>Quantity</td>
					<td>Price</td>
				</tr>

        {% for product in products %}
				<tr class="item">
					<td>{{product.title}}</td>
          <td>{{product.quantity}}</td>
					<td>{{product.currency}} {{product.price}}</td>
				</tr>
        {% endfor %}




				<tr class="total">
					<td></td>

					<td>Total: {{invoiceCurrency}} {{invoiceTotal}}</td>
				</tr>

     



			</table>



		</div>
		

    <script>
        function printpage(divName) {
            var printContents = document.getElementById(divName).innerHTML;
            var originalContents = document.body.innerHTML;
            document.body.innerHTML = printContents;
            window.print();
            document.body.innerHTML = originalContents;
        }       
        </script>
	</body>
</html>